// This file was generated by Mendix Business Modeler 5.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the Microflows for the MyFirstModule module

	public static String currentColor(IContext context, myfirstmodule.proxies.EntityTest _entityTest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EntityTest", _entityTest == null ? null : _entityTest.getMendixObject());
			return (String)Core.execute(context, "MyFirstModule.CurrentColor", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static boolean iVK_EntityTest_Show(IContext context, myfirstmodule.proxies.EntityTest _entityTest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EntityTest", _entityTest == null ? null : _entityTest.getMendixObject());
			return (Boolean)Core.execute(context, "MyFirstModule.IVK_EntityTest_Show", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static String message_nocon(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			return (String)Core.execute(context, "MyFirstModule.message_nocon", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void setColorBlack(IContext context, myfirstmodule.proxies.EntityTest _entityTest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EntityTest", _entityTest == null ? null : _entityTest.getMendixObject());
			Core.execute(context, "MyFirstModule.SetColorBlack", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void setColorPurple(IContext context, myfirstmodule.proxies.EntityTest _entityTest)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			params.put("EntityTest", _entityTest == null ? null : _entityTest.getMendixObject());
			Core.execute(context, "MyFirstModule.SetColorPurple", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}

	public static void showmessage_nocon(IContext context)
	{
		try
		{
			Map<String, Object> params = new HashMap<String, Object>();
			Core.execute(context, "MyFirstModule.showmessage_nocon", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}